version: '3.8'

services:
  musicinteraction.api:
    image: musicinteraction.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__PostgreSQL=Host=${POSTGRES_HOST};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - MongoDB__ConnectionString=${MONGODB_CONNECTION_STRING}
      - MongoDB__DatabaseName=${MONGODB_DATABASE_NAME}
    depends_on:
      - postgres
      - mongodb
    networks:
      - music-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - music-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - music-network

networks:
  music-network:
    driver: bridge

volumes:
  postgres-data:
  mongodb-data: