version: '3.8'

services:
  musicinteraction.api:
    image: musicinteraction.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__PostgreSQL=Host=${POSTGRES_HOST};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - MongoDB__ConnectionString=${MONGODB_CONNECTION_STRING}
      - MongoDB__DatabaseName=${MONGODB_DATABASE_NAME}
      - Cors__AllowedOrigins__0=${FRONTEND_BASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - music-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - music-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27018"
    networks:
      - music-network
    volumes:
      - mongodb-data:/data/db

networks:
  music-network:
    driver: bridge

volumes:
  postgres-data:
  mongodb-data: