name: Build Frontend Application

on:
  push:
    branches: [ main, development ]
    paths:
      - 'frontend/**'
      - '.github/workflows/build-frontend.yml'
    pull_request:
      branches: [ main, development ]
      paths:
        - 'frontend/**'
  workflow_dispatch:
    inputs:
      version_increment:
        description: 'Semantic version increment (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

env:
  REGISTRY: ghcr.io
  ORGANIZATION: ${{ github.repository_owner }}
  APP_NAME: music-app-frontend
  APP_DIR: frontend
  VERSION_FILE: frontend/VERSION
  VITE_API_BASE_URL: /api/v1

jobs:
  build-and-publish:
    name: Build and Publish Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Node.js for testing before Docker build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      # Install dependencies for running tests
      - name: Install Dependencies
        working-directory: ${{ env.APP_DIR }}
        run: npm ci

      # Run linting check
      - name: Run Linting
        working-directory: ${{ env.APP_DIR }}
        run: npm run lint
        continue-on-error: true  # Don't fail the build for linting errors

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Read or create version file
      - name: Read Version File
        id: read_version
        run: |
          if [ -f "${{ env.VERSION_FILE }}" ]; then
            echo "Current version: $(cat ${{ env.VERSION_FILE }})"
            echo "current_version=$(cat ${{ env.VERSION_FILE }})" >> $GITHUB_OUTPUT
          else
            echo "0.1.0" > ${{ env.VERSION_FILE }}
            echo "Current version: 0.1.0"
            echo "current_version=0.1.0" >> $GITHUB_OUTPUT
          fi

      # Determine branch type and set appropriate tags
      - name: Set Tags
        id: set_tags
        run: |
          # Convert organization name to lowercase for Docker compatibility
          ORG_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          if [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
            # development branch tagging
            DATE_TAG="development-$(date +'%Y%m%d-%H%M')"
            TAGS="${{ env.REGISTRY }}/$ORG_LOWER/${{ env.APP_NAME }}:development,${{ env.REGISTRY }}/$ORG_LOWER/${{ env.APP_NAME }}:$DATE_TAG"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Parse current version
            IFS='.' read -r major minor patch <<< "${{ steps.read_version.outputs.current_version }}"
            
            # Determine increment type
            INCREMENT_TYPE="${{ github.event.inputs.version_increment }}"
            
            # Increment version according to semantic versioning
            case "$INCREMENT_TYPE" in
              major)
                major=$((major + 1))
                minor=0
                patch=0
                ;;
              minor)
                minor=$((minor + 1))
                patch=0
                ;;
              patch)
                patch=$((patch + 1))
                ;;
            esac
            
            NEW_VERSION="${major}.${minor}.${patch}"
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            
            TAGS="${{ env.REGISTRY }}/$ORG_LOWER/${{ env.APP_NAME }}:v$NEW_VERSION,${{ env.REGISTRY }}/$ORG_LOWER/${{ env.APP_NAME }}:latest"
            
            # Update version file
            echo "$NEW_VERSION" > ${{ env.VERSION_FILE }}
          else
            # PR or other branches
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
            TAGS="${{ env.REGISTRY }}/$ORG_LOWER/${{ env.APP_NAME }}:$BRANCH_NAME"
          fi
          
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      # Create .env.staging file with secrets
      - name: Create environment file
        run: |
          cat > ${{ env.APP_DIR }}/.env.staging << EOF
          # API Base URL
          VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }}
          
          # Auth0 Configuration
          VITE_AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
          VITE_AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
          EOF

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.APP_DIR }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.set_tags.outputs.tags }}
          build-args: |
            VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }}
            VITE_AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
            VITE_AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Commit version file change and create tag for main branch
      - name: Commit Version Change and Create Tag
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add ${{ env.VERSION_FILE }}
          git commit -m "Bump ${{ env.APP_NAME }} version to ${{ steps.set_tags.outputs.new_version }}"
          
          # Create annotated tag
          git tag -a "${{ env.APP_NAME }}-v${{ steps.set_tags.outputs.new_version }}" -m "Release ${{ env.APP_NAME }} v${{ steps.set_tags.outputs.new_version }}"
          
          # Push both commit and tag
          git push origin HEAD:${{ github.ref_name }}
          git push origin "${{ env.APP_NAME }}-v${{ steps.set_tags.outputs.new_version }}"