name: Backend Code Analysis Pipeline

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'

env:
  # Set Docker registry and organization
  REGISTRY: ghcr.io
  ORGANIZATION: ${{ github.repository_owner }}

  # SonarQube Configuration
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  # Job to analyze code quality on PRs and branch pushes
  analyze:
    name: Analyze Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      # Set up .NET for SonarQube analysis
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Run SonarQube Analysis
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./backend
          args: >
            -Dsonar.projectKey=imdb-for-music
            -Dsonar.organization=yaroslavkse


      # Check for Quality Gate status
      - name: SonarQube Quality Gate Check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 120  # Added timeout as in the example
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}